#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-ss"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5b9b896d88894d1d9f274f4259c544a1" }
]

[assets]
directory = "./public"
